### ISSUE TITLE
request: custom move up\down steps (maybe rotation too)

### ISSUE THREAD

**Issue by Owyn** [kota69th/CreativeExpansionPack#1]
Not being able to move objects up and down precise have been bugging me since the release of creative, maybe you could tone that with the pack? e.g. with an option to set the step to minimum

**Comment by kota69th** [comment]
hey, For these sort of issues concerning precision you might consider checking out UnityExplorer, adding these sort of changes is quite hard and I don't have any plans to make proper updates to the mod, rather some bug fixes and quick patches

as for rotation steps I have tried to include more of them but the code didn't seem like working and I didn't feel like bothering with that
