### ISSUE TITLE
Hello I have a idea what can you guys add to next creative expansion update 

### ISSUE THREAD

**Issue by niotacz** [kota69th/CreativeExpansionPack#11]
I would like to see improvement into a rotating obstacles. a movement speed. Movement speed (very slow, slow, medium, fast, very fast) is not 100% what most of us want Is a number of speed 1-100 example: rotating fan in fast movement is still slow if I would pick number 85 rotating fan would be twice as fast as *movement speed fast* in original creative version if that's doable please add this to new update I would be grateful

**Comment by kota69th** [comment]
hey, unfortunatly everything that kind of involves parameters can't be modified because it wouldn't work while playing in an unmodified copy of the game
