### ISSUE TITLE
Wall overlapping restrictions still there

### ISSUE THREAD

**Issue by Owyn** [kota69th/CreativeExpansionPack#12]
![image](https://github.com/kota69th/CreativeExpansionPack/assets/1309656/3a03189d-b0c9-4c43-ba7a-78e498e5b437)
![image](https://github.com/kota69th/CreativeExpansionPack/assets/1309656/a7d49147-21c7-4526-a4d7-12a0caaea9e1)

would be nice if they got disabled along with all the other overlapping restrictions

**Comment by kota69th** [comment]
true, i might add this
