### ISSUE TITLE
Is there still hope?

### ISSUE THREAD

**Issue by LummaDesign** [kota69th/CreativeExpansionPack#15]
kota,

Is there any news you can tell us about the CEP that is currently no longer usable since the game update.

We need you man! :D

Furthermore, I would like to sincerely thank you for all the work you have done so far.

**Comment by sjinedlime** [comment]
Hope you get it fixed,it’s a great program and it’s no fun without it.

thanks for the time that I had to make great maps.

keep up the good work

**Comment by Axe555** [comment]
he wont, he dont care about being the only person who made fall guys creative finally usable, he will respond to your issue with something like "no" and close it.

**Comment by kota69th** [comment]
> kota,
> 
> Is there any news you can tell us about the CEP that is currently no longer usable since the game update.
> 
> We need you man! :D
> 
> Furthermore, I would like to sincerely thank you for all the work you have done so far.

A new version has been in developement, news on it soon
