### ISSUE TITLE
CEP on Linux?

### ISSUE THREAD

**Issue by shebangcode** [kota69th/CreativeExpansionPack#16]
Hi, I use a Debian pc and I was wondering if the Creative Expansion Pack is compatible with Linux. This mod is very cool but I don't want to take any risks by installing it on linux

**Comment by Owyn** [comment]
what risks?

> if the Creative Expansion Pack is compatible with Linux. 

no idea

**Comment by kota69th** [comment]
It is compatible with Linux, however you're gonna have to install BepinEx manually on your computer and trace back yourself what the Reinstall_BepinEx.bat file does

Good luck and have fun

**Comment by RickRollMaster101** [comment]
You just need to add winhttp to DLL overrides with winecfg for bepinex to work (late I know)

**Comment by shebangcode** [comment]
Alright, thanks! Do yo u think i can trace it back in bash or should i do it in python?
