### ISSUE TITLE
Won’t work

### ISSUE THREAD

**Issue by Adude1999** [kota69th/CreativeExpansionPack#17]
Hello, I recently downloaded the Creative Expansion Pack for the first time and did everything I was supposed to do, drop the files to the Fall guys files and Ran the install_bepinex batch file but when I load up the game it’s just ordinary Fall Guys there’s no creative expansion, please help

**Comment by eightet** [comment]
同感です。私はあなたと同じ症状
がでます。

**Comment by kota69th** [comment]
The mod is pretty much cancelled at this point, you can check out Owyn's unofficial version that is still maitained at this link :
https://github.com/Owyn/CreativeExpansionPack
