### ISSUE TITLE
JOIN NOW WHEN YOU SEE

### ISSUE THREAD

**Issue by MinecraftUserHAN1110** [kota69th/CreativeExpansionPack#4]
I contacted Epic Games directly. They said it was EULA violation, get off immediately.
and, Delete it from Your PC

**Comment by kota69th** [comment]
what are you looking for kid,
if mediatonic or epic games wants to take down they can just contact me and i will cooperate

i have already clarified how the eula is written so thay fall guys has control over their games and its surroudings, and that it's up to them to tell if cep is a threat.

you are scaring no one
