### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by TonicGaro** [kota69th/CreativeExpansionPack#7]
I'm sorry for my inappropriate behavior. I was in a dark place, ever since I was recruited for the hit show Thug Hunter it changed me as a person. I have learned from my actions and have grown as a person. I believe it was Shakespeare who said, "playing with a man's private parts is most sincere form of flattery." but I don't think this is true anymore in the 21st century.

**Comment by kota69th** [comment]
this wasn't thug content bro this was fucking gore
